### ISSUE TITLE
New .burl handler

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#134]
#### Description
**Should**:
* File named *.burl which contains a utf8 encoded url 
* Preview converter, screenshot of web url's 
* (optional) clamav scan web url?
* (optional) elasticsearch index web site content (but an interval task must be added to update the content weekly or so)

web client:
* web ui opens new tab with that url, also must ask if the user wants
* web ui can create a new burl file via "new file" (popup, name, url)

**Comment by juckerf** [comment]
probably use headerless browser microservice for screenshots, convert to pdf ...
(for example: https://github.com/joelgriffith/browserless)

**Comment by raffis** [comment]
Part of v2.1.0-beta1
