### ISSUE TITLE
implement more admin functionality within api (user, group creation, ...)

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#14]

**Comment by juckerf** [comment]
useful endpoints:

> POST /api/v1/user Create acconnt
> POST /api/v1/user/attributes Modify acconnt attributes
> POST /api/v1/group Create group
> DELETE /api/v1/group Delete group
> POST /api/v1/group/attributes Modify group attributes

**Comment by raffis** [comment]
(all those or most of them need to call methods from \Balloon\Server for that, but those are not yet implemented)
