### ISSUE TITLE
Add custom throttle time to subscription

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#155]
#### Description
**Is**:
Subscribe, recursively, not include own changes

**Should**:
It would be nice to have some more options, especially:
* throttle time configurable by user alongside server default

#### balloon server version
2.0.5

**Comment by mathias-noethiger** [comment]
trottle time set to 120sec
Saved file several time time during 2 minutes
only 1 notification was sent.
tested including own changes and shared together with Raffael excluding own changes.
