### ISSUE TITLE
apiv1/v2 colletion size is always 0 if the node gets requested directly

### ISSUE THREAD

**Issue by s-aebischer** [gyselroth/balloon#353]
#### Describe the bug
Attribut "size" is always 0 when running the following api request:
https://<servername>/api/v1/node/attributes?p=<path>
Though the path has subfolders or files

**Comment by raffis** [comment]
This bug also applies to v2 and is a follow error from #343

**Comment by raffis** [comment]
The bug does not apply if the nodes are requested via a list call (/nodes or /children, ...)
