### ISSUE TITLE
Do not send notification based on temporary file changes

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#378]
#### Describe the change
balloon shold not send notifications for temporary files.

#### Current situation
Currently balloon sends notifications for files like `~$Meinfile.docx`

#### Should
Ignore notifications for temporary files:
https://github.com/gyselroth/balloon/blob/master/src/lib/Filesystem/Node/File.php#L44

(Also add ^\~\$ file to that list)

**Comment by mathias-noethiger** [comment]
is not yet working

![image](https://user-images.githubusercontent.com/21195302/74515444-daf75480-4f0e-11ea-9e0b-ffccfc8e6e7a.png)

**Comment by raffis** [comment]
Lets match any files starting with `~` as temporary.

**Comment by mathias-noethiger** [comment]
it worked with regularly created temp files on my Mac 
![image](https://user-images.githubusercontent.com/21195302/74519085-5b20b880-4f15-11ea-9018-967a6625048d.png)

![image](https://user-images.githubusercontent.com/21195302/74519155-7e4b6800-4f15-11ea-972b-d2426b967073.png)

**Comment by danielkleeb** [comment]
Close the tested issue.
