### ISSUE TITLE
Newly added folders from other users within a share get not added to other users descriptions

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#406]
#### Current situation
When a new sub folder gets added a new subscription for this folder gets created, but only
for the user who created the sub folder. If another user also has an active subscription for the parent no new subscription gets made.

Another problem is how to remove such subscriptions. If a new subscriptions gets made for each sub collection it is currently not possible to remove all subscriptions from the parent collection. One has to remove each and every subscription from each node.

#### Should
The subscription should only be hold by the parent node.
No new subscriptions shall be made after adding new sub collections. 
While a change occurs the notifier must fetch all subscripts from parent nodes and send the notification.

**Attention**: Shares are holders of subscriptions and not the references.

**Comment by mathias-noethiger** [comment]
case 1:
I created a folder and shared it and subscribed to it including own changes
As shared user I subscribed to that folder the same way.

A: works as expected
I created a new subfolder over the browser (all folders empty)
- no notification to me 
- 1 notification about this new subfolder for the shared user. 

B: 
I created a new subfolder over the desktop client
- no notification for the shared user got sent. 

case 2:
I added an additional subscription to a subfolder of an already subscribed folder as owner (including own changes) and as shared user. 
A
- I then removed subscription from superfolder (parent folder).
-> No subscription was sent nor to the owner, not to the shared user -> OK
-> this subscription settings are still set for the subfolder and visible by the speaker icon. Even the setting is still there it does not work anymore. -> NOT OK. Gap between settings and reality. 

B
As owner and shared user I removed the no more working setting saved and set it the same way again and saved again. 
Subscription setting is working again. -> OK

Conclusion: If a parent setting is changing a subsetting the GUI should also show the new situation.
