### ISSUE TITLE
Deleted node not represented in delta

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon#408]
#### Describe the bug
When deleting a node and renaming another node to the name of the deleted node, this is not represented in the delta.

#### To Reproduce
1.) Create collection `/a` and nodes `/a/a.txt` (ID: `5dc9b2855adea077926c2e80`) and `/a/b.txt` (ID: `5dc9b28d5adea077926c2e95`) 
2.) Call `/api/v1/node/delta` note cursor (`ZGVsdGF8MHwwfDVkYzliMjhkNWFkZWEwNzc5MjZjMmVhOHwxNTczNDk5NTMzNTc4`)
3.) Delete `/a/a.txt` 
4.) Rename `/a/b.txt` to `/a/a.txt`
5.) Call delta with cursor from step 2.)

The delted node `5dc9b2855adea077926c2e80` is not present in the delta.

```
{
  "status": 200,
  "data": {
    "reset": false,
    "cursor": "ZGVsdGF8MHwwfDVkYzliMmRiNWFkZWEwNzc5MjZjMmViMHwxNTczNDk5NjExMTEz",
    "has_more": false,
    "nodes": [
      {
        "id": "5dc9b28d5adea077926c2e95",
        "directory": false,
        "path": "\/a\/a.txt",
        "created": {
          "sec": "1573499533",
          "usec": "517000"
        },
        "changed": {
          "sec": "1573499533",
          "usec": "542000"
        },
        "deleted": false
      },
      {
        "id": "5dc9b28d5adea077926c2e95",
        "deleted": true,
        "changed": {
          "sec": "1573499611",
          "usec": "113000"
        },
        "path": "\/a\/b.txt"
      }
    ]
  }
}
```

#### Expected behavior
Node should be present:
```
{
  "status": 200,
  "data": {
    "reset": false,
    "cursor": "ZGVsdGF8MHwwfDVkYzliMmRiNWFkZWEwNzc5MjZjMmViMHwxNTczNDk5NjExMTEz",
    "has_more": false,
    "nodes": [
      {
        "id": "5dc9b2855adea077926c2e80",
        "deleted": true,
        "changed": {
          "sec": "1573499609",
          "usec": "223000"
        },
        "path": "\/a\/b.txt"
      },
      {
        "id": "5dc9b28d5adea077926c2e95",
        "directory": false,
        "path": "\/a\/a.txt",
        "created": {
          "sec": "1573499533",
          "usec": "517000"
        },
        "changed": {
          "sec": "1573499533",
          "usec": "542000"
        },
        "deleted": false
      },
      {
        "id": "5dc9b28d5adea077926c2e95",
        "deleted": true,
        "changed": {
          "sec": "1573499611",
          "usec": "113000"
        },
        "path": "\/a\/b.txt"
      }
    ]
  }
}
```

#### Environment
 - balloon server version: v2.6.7
 - Deployed as: docker
 - PHP version: ?
 - MongoDB version: ?

**Comment by raffis** [comment]
This is not a bug and by design. The api endpoint /api/v1/node/delta (and /api/v2/nodes/delta)  works by file paths to be compatible with legacy systems.
Therefore there can only be one entry for each node within the delta.

If unique identification for nodes is required the event endpoint should be used. Note in the upcoming v3 there will be a new /api/v3/events endpoint which also supports something similar like a cursor (skip tokens) (Note those skip cursors will be supported by all endpoints which return a List).
