### ISSUE TITLE
build.sh doesn't provide src/httpdocs/ui/locale/build.<lang>.json

### ISSUE THREAD

**Issue by juckerf** [gyselroth/balloon#43]
only provides src/httpdocs/ui/locale/<lang>.json
I assume build.<lang>.json is dynamically built depending on enabled apps?
How do one create such a build.<lang>.json?

**Comment by raffis** [comment]
@juckerf Do you have all requirements installed to build? see #37

**Comment by juckerf** [comment]
@raffis sorry, my bad. the yui-compressor was not executed because the phpunit scripts failed and the scripts aborted
