### ISSUE TITLE
Allow filter to be set by query string

### ISSUE THREAD

**Issue by pixtron** [gyselroth/balloon#51]
Various endpoints offer an optional parameter to filter the response (eg: `GET /collection/children`).
The filter parameter has to be JSON. 

If a api consumer want's to filter the response, he either has to submit all parameters including the filter parameter

1.  as JSON in the request body (eg: `{"p": "/parentNode", "filter": {"directory": true}}`)
2. as JSON in the query string (eg: `?{"p": "/parentNode", "filter": {"directory": true}}`)

For all other parameters, except the ones which require json, it is possible to submit them by query string with key value pairs (eg: `?p=/parentNode`).

It would be nice to have the option to supply the filter parameter as well as key value pair, so the filter can be mixed with other query string parameters (eg: `?p=/parentNode&filter={"directory": true}`).

**Comment by raffis** [comment]
going to integrate this in the v2 branch combined with enhancements in \Micro

**Comment by raffis** [comment]
#129

**Comment by raffis** [comment]
This issue has been fixed in v2.3.3 for the api v2 only.
